-- MySQL Script generated by MySQL Workbench
-- Wed Jul 23 15:14:40 2025
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`donante`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`donante` (
  `id_donante` VARCHAR(10) NOT NULL,
  `grupo_sanguineo` VARCHAR(45) NULL,
  `factor_rh` VARCHAR(45) NULL,
  `nombre_donante` VARCHAR(100) NULL,
  `direccion` VARCHAR(100) NULL,
  `numero_telefono` VARCHAR(11) NULL,
  `email` VARCHAR(100) NULL,
  `edad` INT NULL,
  `genero` VARCHAR(15) NULL,
  PRIMARY KEY (`id_donante`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`inventario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`inventario` (
  `id_inventario` VARCHAR(10) NOT NULL,
  `unidad` VARCHAR(5) NULL,
  `congelador` VARCHAR(5) NULL,
  `almacen` VARCHAR(10) NULL,
  PRIMARY KEY (`id_inventario`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`emparejamiento`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`emparejamiento` (
  `grupo_sanguineo` VARCHAR(20) NULL,
  `factor_rh` VARCHAR(15) NULL,
  `id_emparejamiento` VARCHAR(10) NOT NULL,
  `donante_id_donante` VARCHAR(10) NOT NULL,
  `inventario_id_inventario` VARCHAR(10) NOT NULL,
  PRIMARY KEY (`id_emparejamiento`, `donante_id_donante`, `inventario_id_inventario`),
  INDEX `fk_emparejamiento_donante_idx` (`donante_id_donante` ASC) VISIBLE,
  INDEX `fk_emparejamiento_inventario1_idx` (`inventario_id_inventario` ASC) VISIBLE,
  CONSTRAINT `fk_emparejamiento_donante`
    FOREIGN KEY (`donante_id_donante`)
    REFERENCES `mydb`.`donante` (`id_donante`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_emparejamiento_inventario1`
    FOREIGN KEY (`inventario_id_inventario`)
    REFERENCES `mydb`.`inventario` (`id_inventario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
